Feature/account page improvement
unopim/unopim pull request #32
Opened 2024-09-30 10:45 UTC by vipin-webkul

## Issue Reference

## Description

## How To Test This?

## Documentation
- [ ] My pull request requires an update on the documentation repository.

## Branch Selection

- [ ] Target Branch: master 

## Pint

## Tailwind Reordering

2024-09-30 11:17 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
> +                            :options="$locales"
The options can be added like this without the need of an extra variable:
```php
:options="core()->getAllActiveLocales()"
```

2024-09-30 11:17 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Resources/views/account/edit.blade.php
> +                            :options="$timezones"
Here too the options can be added like this without the need of an extra variable:
```php
:options="json_encode(core()->getTimeZones())"
```

2024-09-30 11:18 UTC, devansh-pal-webkul commented on packages/Webkul/User/tests/Feature/UserTest.php
> +    $admin = Admin::factory()->create([
Remove this from all the test cases as it is not being used.

2024-09-30 11:21 UTC, devansh-pal-webkul commented on packages/Webkul/User/tests/Feature/UserTest.php
> +    $response->assertRedirect();
Both are same only need to use one assertRedirect checks for the status code 302 also.
```php
    $response->assertRedirect();
```

2024-09-30 11:21 UTC, devansh-pal-webkul requested changes
@vipin-webkul, please make the requested changes.

2024-10-01 06:24 UTC, vipin-webkul commented
@devansh-pal-webkul 
I have updated the code as mentioned.
Please check.

2024-10-09 13:34 UTC, merged