Added dynamic configuration for import filters similar to export filters
unopim/unopim pull request #80
Opened 2024-12-23 06:38 UTC by pravat-senapati

2024-12-24 04:53 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
> +            'action' => 'fetch',
Change this to create/update instead of fetch

2024-12-24 04:55 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
> +            request()->except(['_token', 'code']),
Use only here to limit what data is allowed also just add 'filters' for its value

2024-12-24 04:56 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Resources/lang/ar_AE/app.php
> +                    'delete-failure-Attr' => 'لا يمكن إزالة هذه السمة لأنها مستخدمة كسمة متغيرة',
change translation key name to 'delete-attribute-failure' in all places

2024-12-24 04:59 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/create.blade.php
> +                        console.log(value);
remove console.log

2024-12-24 05:04 UTC, devansh-pal-webkul commented on packages/Webkul/DataTransfer/src/Validators/JobInstances/Default/JobValidator.php
> +    public function validate(array $data, array $option = []): void
change to options instead of option

2025-01-02 07:34 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/edit.blade.php
> +    <v-import-profile-edit></v-import-profile-edit>
This page can work without the component as job type does not change here. Check and update if this page can be used without this component

2025-01-02 07:39 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/create.blade.php
> +                },
no use for this listener and this function handleFilterValues.

2025-01-02 13:08 UTC, devansh-pal-webkul requested changes
@pravat-senapati , please update the specified changes

2025-01-03 04:36 UTC, pravat-senapati commented on packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
> +            'action' => 'fetch',
https://github.com/pravat-senapati/unopim/blob/830a7050a6363b6bd3ea009cbe95f552a5b84664/packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php#L91

Updated

2025-01-03 04:39 UTC, pravat-senapati commented on packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
> +            request()->except(['_token', 'code']),
https://github.com/pravat-senapati/unopim/blob/830a7050a6363b6bd3ea009cbe95f552a5b84664/packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php#L153

Updated

2025-01-03 04:40 UTC, pravat-senapati commented on packages/Webkul/Admin/src/Resources/lang/ar_AE/app.php
> +                    'delete-failure-Attr' => 'لا يمكن إزالة هذه السمة لأنها مستخدمة كسمة متغيرة',
https://github.com/pravat-senapati/unopim/blob/830a7050a6363b6bd3ea009cbe95f552a5b84664/packages/Webkul/Admin/src/Resources/lang/ar_AE/app.php#L296

Updated

2025-01-03 04:41 UTC, pravat-senapati commented on packages/Webkul/Admin/src/Resources/views/settings/data-transfer/imports/create.blade.php
> +                        console.log(value);
Updated

2025-01-03 04:42 UTC, pravat-senapati commented on packages/Webkul/DataTransfer/src/Validators/JobInstances/Default/JobValidator.php
> +    public function validate(array $data, array $option = []): void
https://github.com/pravat-senapati/unopim/blob/830a7050a6363b6bd3ea009cbe95f552a5b84664/packages/Webkul/DataTransfer/src/Validators/JobInstances/Default/JobValidator.php#L32

Updated

2025-01-03 06:31 UTC, pravat-senapati commented
@devansh-pal-webkul 
Update changes

2025-02-06 06:20 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php
> +            ], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
Change response code to JsonResponse::HTTP_BAD_REQUEST

2025-02-06 06:25 UTC, devansh-pal-webkul commented on packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
> +        $importerConfig = config('importers');
use constant here for 'importers' key.

2025-02-06 06:27 UTC, devansh-pal-webkul requested changes
@pravat-senapati , please update the requested changes

2025-02-06 06:46 UTC, pravat-senapati commented on packages/Webkul/Admin/src/Http/Controllers/Settings/DataTransfer/ImportController.php
> +        $importerConfig = config('importers');
Fixed

2025-02-06 06:46 UTC, pravat-senapati commented on packages/Webkul/Admin/src/Http/Controllers/Catalog/AttributeController.php
> +            ], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
fixed

2025-02-06 06:47 UTC, pravat-senapati commented
@devansh-pal-webkul 
Changes Done please check

2025-02-06 06:49 UTC, devansh-pal-webkul approved these changes

2025-02-06 06:58 UTC, merged